stm32f030R8 board support for helloworld
Temple-Mountain-Robotics/beetree-examples pull request #6
Opened 2021-07-28 04:11 UTC by mattmercaldo

- core code for stm32f030R8 board
- add mac installation manual
- updated readme for the stm32f030 board.

2021-07-28 04:14 UTC, mattmercaldo commented on helloworld/platform/src/stm32f030x8/internal-platform.hpp
> +        stm32f0xx::DiscreteOutput           led;
to ease flush and sync i put the hardware into the controllers. 
I think this makes sense.. The other way made me have to access the singleton.

2021-07-29 04:36 UTC, rudx0029 requested changes
Just clean up the call to the singleton within the member functions.

2021-07-29 04:36 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/boot.cpp
> +bool InternalPlatform::boot()
~~This needs to stay as `boot`. It is called directly from the application as `helloworld::boot()`~~
NM.  I see the changes below.

2021-07-29 04:36 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/internal-platform.cpp
> +    InternalPlatform &platform = InternalPlatform::instance();
There no need for this  `InternalPlatform &platform = InternalPlatform::instance();` in a member function. The instance is always `this`. `InternalPlatform &platform = InternalPlatform::instance();`  can you get you in trouble pretty quickly when used in an instance method.

2021-07-29 04:36 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/internal-platform.cpp
> +    InternalPlatform &platform = InternalPlatform::instance();
TODO: Remove all references to `InternalPlatform::instance()` when used in a member function.

2021-07-29 04:36 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/internal-platform.cpp
> +bool boot(Platform &) { return InternalPlatform::instance().boot(); }
It is okay to call `InternalPlatform::instance()` here because `boot` is not a member function.

```cpp
class InternalPlatform
{
      void member_function() { /* do not call InternalPlatform::instance() */ }
     static void static_member_function() { /*ok to call*/ InternalPlatform::instance(); }
};

2021-07-29 04:36 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/internal-platform.cpp
>  bte::ISystemClock& Platform::clock() { return InternalPlatform::instance().clock; }
okay to call `InternalPlatform::instance()` since it is not a member of `Platform`

2021-07-29 05:17 UTC, mattmercaldo commented on helloworld/platform/src/stm32f030x8/internal-platform.cpp
> +    InternalPlatform &platform = InternalPlatform::instance();
good catch - this was old junk not referenced - it went away when i make the hardware local to the class

2021-07-29 06:02 UTC, rudx0029 requested changes

2021-07-29 06:02 UTC, rudx0029 commented on helloworld/platform/src/stm32f030x8/boot.cpp
>      InternalPlatform &platform = InternalPlatform::instance();
One more to go... I didn't realize it was spread across two files.

2021-07-29 06:03 UTC, rudx0029 commented
Just to note, I really don't like git hubs review interface.

2021-07-29 16:22 UTC, merged